# Set the build language to Python
language: python

python: 3.7

# Install the codecov pip dependency
install:
  - pip install codecov
  - pip install matplotlib
  - pip install numpy
  - pip install coverage

script:
  - coverage run tests/CI/seir.py
  - coverage run tests/CI/sihrd.py
  - coverage run tests/CI/sir.py
  - coverage run tests/CI/sird.py

# Push the results back to codecov
after_success:
  - codecov
