# Set the build language to Python
language: python

python: 3.7

# Install the codecov pip dependency
install:
  - pip install codecov
  - pip install matplotlib
  - pip install numpy
  - pip install coverage

script:
  - cd tests/CI
  - python test_sir.py
  - python test_seir.py
  - python test_sird.py
  - python test_sihrd.py
